Config = {}
--[[
=================================================
        NControl - Configuration
=================================================
]]

Config.Debug = true -- Debug messages printed to console

Config.DisablePopulation = false -- Will completely disable the population

Config.PedPopulationBudget = 2 -- 0 - 3 - Memory budget for all peds
Config.VehiclePopulationBudget = 2 -- 0 - 3 - Memory budget for all NPC vehicles
Config.ReduceVehicleModelVariance = false -- Reduces the variety of vehicle models on the map
Config.ReducePedModelVariance = false -- Reduces the variety of PED models

Config.PopulationDisabledBuckets = {  -- Routing buckets where PED population is disabled
	-- 1,
	-- 3,
	-- 5
}

--[[ 
Toggle dispatch services
false = disabled
true = enabled
]]
Config.EnabledDispatchServices = {
	PoliceAutomobile = false,
	PoliceHelicopter = false,
	FireDepartment = false,
	SwatAutomobile = false,
	AmbulanceDepartment = false,
	PoliceRiders = false,
	PoliceVehicleRequest = false,
	PoliceRoadBlock = false,
	PoliceAutomobileWaitPulledOver = false,
	PoliceAutomobileWaitCruising = false,
	Gangs = true,
	SwatHelicopter = false,
	PoliceBoat = false,
	ArmyVehicle = false,
	BikerBackup = false,
}

--[[
Toggle scenario groups
false = disabled
true = enabled
]]
Config.EnabledScenarioGroups = {
	ALAMO_PLANES = false,
	ARMENIAN_CATS = false,
	ARMY_GUARD = false,
	ARMY_HELI = false,
	ATTRACT_PAP = false,
	BLIMP = false,
	CHINESE2_HILLBILLIES = false,
	Chinese2_Lunch = false,
	Cinema_Downtown = false,
	Cinema_Morningwood = false,
	Cinema_Textile = false,
	City_Banks = false,
	Countryside_Banks = false,
	DEALERSHIP = false,
	FIB_GROUP_1 = true,
	FIB_GROUP_2 = true,
	GRAPESEED_PLANES = false,
	KORTZ_SECURITY = false,
	LOST_BIKERS = false,
	LSA_Planes = false,
	MOVIE_STUDIO_SECURITY = true,
	MP_POLICE = false,
	Observatory_Bikers = false,
	POLICE_POUND1 = false,
	POLICE_POUND2 = false,
	POLICE_POUND3 = false,
	POLICE_POUND4 = false,
	POLICE_POUND5 = false,
	PRISON_TOWERS = true,
	QUARRY = false,
	Rampage1 = false,
	SANDY_PLANES = false,
	SCRAP_SECURITY = false,
	SEW_MACHINE = false,
	SOLOMON_GATE = false,
	Triathlon_1 = false,
	Triathlon_1_Start = false,
	Triathlon_2 = false,
	Triathlon_2_Start = false,
	Triathlon_3 = false,
	Triathlon_3_Start = false,
}

--[[
Toggle specific scenario types
false = disabled
true = enabled
]]
Config.EnabledScenarioTypes = {
	WORLD_HUMAN_AA_COFFEE = true,
	WORLD_HUMAN_AA_SMOKE = true,
	WORLD_HUMAN_BINOCULARS = false,
	WORLD_HUMAN_BUM_FREEWAY = false,
	WORLD_HUMAN_BUM_SLUMPED = true,
	WORLD_HUMAN_BUM_STANDING = true,
	WORLD_HUMAN_BUM_WASH = true,
	WORLD_HUMAN_CAR_PARK_ATTENDANT = false,
	WORLD_HUMAN_CHEERING = false,
	WORLD_HUMAN_CLIPBOARD = true,
	WORLD_HUMAN_CLIPBOARD_FACILITY = true,
	WORLD_HUMAN_CONST_DRILL = false,
	WORLD_HUMAN_COP_IDLES = false,
	WORLD_HUMAN_DRINKING = true,
	WORLD_HUMAN_DRINKING_FACILITY = true,
	WORLD_HUMAN_DRINKING_CASINO_TERRACE = true,
	WORLD_HUMAN_DRUG_DEALER = true,
	WORLD_HUMAN_DRUG_DEALER_HARD = true,
	WORLD_HUMAN_DRUG_FIELD_WORKERS_RAKE = false,
	WORLD_HUMAN_DRUG_FIELD_WORKERS_WEEDING = true,
	WORLD_HUMAN_DRUG_PROCESSORS_COKE = false,
	WORLD_HUMAN_DRUG_PROCESSORS_WEED = false,
	WORLD_HUMAN_MOBILE_FILM_SHOCKING = false,
	WORLD_HUMAN_GARDENER_LEAF_BLOWER = true,
	WORLD_HUMAN_GARDENER_PLANT = true,
	WORLD_HUMAN_GOLF_PLAYER = false,
	WORLD_HUMAN_GUARD_PATROL = false,
	WORLD_HUMAN_GUARD_STAND = false,
	WORLD_HUMAN_GUARD_STAND_CASINO = false,
	WORLD_HUMAN_GUARD_STAND_CLUBHOUSE = false,
	WORLD_HUMAN_GUARD_STAND_FACILITY = false,
	WORLD_HUMAN_GUARD_STAND_ARMY = true,
	WORLD_HUMAN_HAMMERING = false,
	WORLD_HUMAN_HANG_OUT_STREET = false,
	WORLD_HUMAN_HANG_OUT_STREET_CLUBHOUSE = false,
	WORLD_HUMAN_HIKER = false,
	WORLD_HUMAN_HIKER_STANDING = false,
	WORLD_HUMAN_HUMAN_STATUE = false,
	WORLD_HUMAN_INSPECT_CROUCH = false,
	WORLD_HUMAN_INSPECT_STAND = false,
	WORLD_HUMAN_JANITOR = false,
	WORLD_HUMAN_JOG = true,
	WORLD_HUMAN_JOG_STANDING = true,
	WORLD_HUMAN_LEANING = true,
	WORLD_HUMAN_LEANING_CASINO_TERRACE = true,
	WORLD_HUMAN_MAID_CLEAN = true,
	WORLD_HUMAN_MUSCLE_FLEX = false,
	WORLD_HUMAN_MUSCLE_FREE_WEIGHTS = false,
	WORLD_HUMAN_MUSICIAN = true,
	WORLD_HUMAN_PAPARAZZI = false,
	WORLD_HUMAN_PARTYING = true,
	WORLD_HUMAN_PICNIC = true,
	WORLD_HUMAN_POWER_WALKER = false,
	WORLD_HUMAN_PROSTITUTE_HIGH_CLASS = true,
	WORLD_HUMAN_PROSTITUTE_LOW_CLASS = true,
	WORLD_HUMAN_PUSH_UPS = false,
	WORLD_HUMAN_SEAT_LEDGE = true,
	WORLD_HUMAN_SEAT_LEDGE_EATING = true,
	WORLD_HUMAN_SEAT_STEPS = true,
	WORLD_HUMAN_SEAT_WALL = true,
	WORLD_HUMAN_SEAT_WALL_EATING = true,
	WORLD_HUMAN_SEAT_WALL_TABLET = false,
	WORLD_HUMAN_SECURITY_SHINE_TORCH = true,
	WORLD_HUMAN_SIT_UPS = false,
	WORLD_HUMAN_SMOKING = true,
	WORLD_HUMAN_SMOKING_CLUBHOUSE = false,
	WORLD_HUMAN_SMOKING_POT = false,
	WORLD_HUMAN_SMOKING_POT_CLUBHOUSE = false,
	WORLD_HUMAN_STAND_FIRE = false,
	WORLD_HUMAN_STAND_FISHING = true,
	WORLD_HUMAN_STAND_IMPATIENT = false,
	WORLD_HUMAN_STAND_IMPATIENT_CLUBHOUSE = false,
	WORLD_HUMAN_STAND_IMPATIENT_FACILITY = false,
	WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT = false,
	WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT_FACILITY = false,
	WORLD_HUMAN_STAND_MOBILE = false,
	WORLD_HUMAN_STAND_MOBILE_CLUBHOUSE = false,
	WORLD_HUMAN_STAND_MOBILE_FACILITY = false,
	WORLD_HUMAN_STAND_MOBILE_UPRIGHT = false,
	WORLD_HUMAN_STAND_MOBILE_UPRIGHT_CLUBHOUSE = false,
	WORLD_HUMAN_STRIP_WATCH_STAND = false,
	WORLD_HUMAN_STUPOR = false,
	WORLD_HUMAN_STUPOR_CLUBHOUSE = false,
	WORLD_HUMAN_WINDOW_SHOP_BROWSE_SHOWROOM = false,
	WORLD_HUMAN_SUNBATHE = true,
	WORLD_HUMAN_SUNBATHE_BACK = true,
	WORLD_HUMAN_SUPERHERO = false,
	WORLD_HUMAN_SWIMMING = true,
	WORLD_HUMAN_TENNIS_PLAYER = false,
	WORLD_HUMAN_TOURIST_MAP = true,
	WORLD_HUMAN_TOURIST_MOBILE = false,
	WORLD_HUMAN_VALET = true,
	WORLD_HUMAN_VEHICLE_MECHANIC = false,
	WORLD_HUMAN_WELDING = true,
	WORLD_HUMAN_WINDOW_SHOP_BROWSE = true,
	WORLD_HUMAN_YOGA = false,
	PROP_HUMAN_ATM = true,
	PROP_HUMAN_BBQ = true,
	PROP_HUMAN_BUM_BIN = true,
	PROP_HUMAN_BUM_SHOPPING_CART = true,
	PROP_HUMAN_MUSCLE_CHIN_UPS = false,
	PROP_HUMAN_MUSCLE_CHIN_UPS_ARMY = true,
	PROP_HUMAN_MUSCLE_CHIN_UPS_PRISON = true,
	PROP_HUMAN_PARKING_METER = false,
	PROP_HUMAN_SEAT_ARMCHAIR = false,
	PROP_HUMAN_SEAT_BAR = true,
	PROP_HUMAN_SEAT_BENCH = true,
	PROP_HUMAN_SEAT_BENCH_FACILITY = true,
	PROP_HUMAN_SEAT_BENCH_DRINK = true,
	PROP_HUMAN_SEAT_BENCH_DRINK_FACILITY = true,
	PROP_HUMAN_SEAT_BENCH_DRINK_BEER = true,
	PROP_HUMAN_SEAT_BENCH_FOOD = true,
	PROP_HUMAN_SEAT_BENCH_FOOD_FACILITY = true,
	PROP_HUMAN_SEAT_BUS_STOP_WAIT = true,
	PROP_HUMAN_SEAT_CHAIR = true,
	PROP_HUMAN_SEAT_CHAIR_DRINK = true,
	PROP_HUMAN_SEAT_CHAIR_DRINK_BEER = true,
	PROP_HUMAN_SEAT_CHAIR_FOOD = true,
	PROP_HUMAN_SEAT_CHAIR_UPRIGHT = true,
	PROP_HUMAN_SEAT_CHAIR_UPRIGHT_SHOWROOM = false,
	PROP_HUMAN_SEAT_CHAIR_MP_PLAYER = true,
	PROP_HUMAN_SEAT_COMPUTER = true,
	PROP_HUMAN_SEAT_COMPUTER_LOW = false,
	PROP_HUMAN_SEAT_DECKCHAIR = false,
	PROP_HUMAN_SEAT_DECKCHAIR_DRINK = false,
	PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS = false,
	PROP_HUMAN_SEAT_MUSCLE_BENCH_PRESS_PRISON = false,
	PROP_HUMAN_SEAT_SEWING = false,
	PROP_HUMAN_SEAT_STRIP_WATCH = true,
	PROP_HUMAN_SEAT_SUNLOUNGER = true,
	PROP_HUMAN_STAND_IMPATIENT = false,
	CODE_HUMAN_COWER = true,
	CODE_HUMAN_CROSS_ROAD_WAIT = true,
	CODE_HUMAN_PARK_CAR = true,
	PROP_HUMAN_MOVIE_BULB = false,
	PROP_HUMAN_MOVIE_STUDIO_LIGHT = false,
	CODE_HUMAN_MEDIC_KNEEL = true,
	CODE_HUMAN_MEDIC_TEND_TO_DEAD = true,
	CODE_HUMAN_MEDIC_TIME_OF_DEATH = true,
	CODE_HUMAN_POLICE_CROWD_CONTROL = false,
	CODE_HUMAN_POLICE_INVESTIGATE = false,
	CHAINING_ENTRY = true,
	CHAINING_EXIT = true,
	CODE_HUMAN_STAND_COWER = true,
	EAR_TO_TEXT = false,
	EAR_TO_TEXT_FAT = false,
	WORLD_LOOKAT_POINT = true,
	WORLD_VEHICLE_ATTRACTOR = false,
	PARK_VEHICLE = true,
	WORLD_VEHICLE_AMBULANCE = false,
	WORLD_VEHICLE_BICYCLE_BMX = true,
	WORLD_VEHICLE_BICYCLE_BMX_BALLAS = true,
	WORLD_VEHICLE_BICYCLE_BMX_FAMILY = false,
	WORLD_VEHICLE_BICYCLE_BMX_HARMONY = false,
	WORLD_VEHICLE_BICYCLE_BMX_VAGOS = true,
	WORLD_VEHICLE_BICYCLE_MOUNTAIN = false,
	WORLD_VEHICLE_BICYCLE_ROAD = false,
	WORLD_VEHICLE_BIKE_OFF_ROAD_RACE = false,
	WORLD_VEHICLE_BIKER = false,
	WORLD_VEHICLE_BOAT_IDLE = true,
	WORLD_VEHICLE_BOAT_IDLE_ALAMO = false,
	WORLD_VEHICLE_BOAT_IDLE_MARQUIS = false,
	WORLD_VEHICLE_BROKEN_DOWN = false,
	WORLD_VEHICLE_BUSINESSMEN = true,
	WORLD_VEHICLE_HELI_LIFEGUARD = false,
	WORLD_VEHICLE_CLUCKIN_BELL_TRAILER = false,
	WORLD_VEHICLE_CONSTRUCTION_SOLO = false,
	WORLD_VEHICLE_CONSTRUCTION_PASSENGERS = false,
	WORLD_VEHICLE_DRIVE_PASSENGERS = true,
	WORLD_VEHICLE_DRIVE_PASSENGERS_LIMITED = false,
	WORLD_VEHICLE_DRIVE_SOLO = true,
	WORLD_VEHICLE_FARM_WORKER = false,
	WORLD_VEHICLE_FIRE_TRUCK = false,
	WORLD_VEHICLE_EMPTY = true,
	WORLD_VEHICLE_MARIACHI = false,
	WORLD_VEHICLE_MECHANIC = false,
	WORLD_VEHICLE_MILITARY_PLANES_BIG = false,
	WORLD_VEHICLE_MILITARY_PLANES_SMALL = false,
	WORLD_VEHICLE_PARK_PARALLEL = true,
	WORLD_VEHICLE_PARK_PERPENDICULAR_NOSE_IN = true,
	WORLD_VEHICLE_PASSENGER_EXIT = true,
	WORLD_VEHICLE_POLICE_BIKE = false,
	WORLD_VEHICLE_POLICE_CAR = false,
	WORLD_VEHICLE_POLICE_NEXT_TO_CAR = false,
	WORLD_VEHICLE_QUARRY = false,
	WORLD_VEHICLE_SALTON = false,
	WORLD_VEHICLE_SALTON_DIRT_BIKE = false,
	WORLD_VEHICLE_SECURITY_CAR = false,
	WORLD_VEHICLE_STREETRACE = true,
	WORLD_VEHICLE_TOURBUS = false,
	WORLD_VEHICLE_TOURIST = false,
	WORLD_VEHICLE_TANDL = false,
	WORLD_VEHICLE_TRACTOR = false,
	WORLD_VEHICLE_TRACTOR_BEACH = false,
	WORLD_VEHICLE_TRUCK_LOGS = true,
	WORLD_VEHICLE_TRUCKS_TRAILERS = true,
	WORLD_VEHICLE_DISTANT_EMPTY_GROUND = false,
	WORLD_BOAR_GRAZING = false,
	WORLD_CAT_SLEEPING_GROUND = false,
	WORLD_CAT_SLEEPING_LEDGE = false,
	WORLD_COW_GRAZING = false,
	WORLD_COYOTE_HOWL = false,
	WORLD_COYOTE_REST = false,
	WORLD_COYOTE_WANDER = false,
	WORLD_COYOTE_WALK = false,
	WORLD_CHICKENHAWK_FEEDING = false,
	WORLD_CHICKENHAWK_STANDING = false,
	WORLD_CORMORANT_STANDING = false,
	WORLD_CROW_FEEDING = false,
	WORLD_CROW_STANDING = false,
	WORLD_DEER_GRAZING = false,
	WORLD_DOG_BARKING_ROTTWEILER = false,
	WORLD_DOG_BARKING_RETRIEVER = false,
	WORLD_DOG_BARKING_SHEPHERD = false,
	WORLD_DOG_SITTING_ROTTWEILER = false,
	WORLD_DOG_SITTING_RETRIEVER = false,
	WORLD_DOG_SITTING_SHEPHERD = false,
	WORLD_DOG_BARKING_SMALL = false,
	WORLD_DOG_SITTING_SMALL = false,
	WORLD_DOLPHIN_SWIM = true,
	WORLD_FISH_FLEE = true,
	WORLD_FISH_IDLE = true,
	WORLD_GULL_FEEDING = true,
	WORLD_GULL_STANDING = true,
	WORLD_HEN_FLEE = false,
	WORLD_HEN_PECKING = false,
	WORLD_HEN_STANDING = false,
	WORLD_MOUNTAIN_LION_REST = true,
	WORLD_MOUNTAIN_LION_WANDER = true,
	WORLD_ORCA_SWIM = true,
	WORLD_PIG_GRAZING = true,
	WORLD_PIGEON_FEEDING = true,
	WORLD_PIGEON_STANDING = true,
	WORLD_RABBIT_EATING = true,
	WORLD_RABBIT_FLEE = true,
	WORLD_RATS_EATING = true,
	WORLD_RATS_FLEEING = true,
	WORLD_SHARK_SWIM = true,
	WORLD_SHARK_HAMMERHEAD_SWIM = true,
	WORLD_STINGRAY_SWIM = true,
	WORLD_WHALE_SWIM = true,
	PROP_BIRD_IN_TREE = true,
	PROP_BIRD_TELEGRAPH_POLE = false,
}

--[[
Toggle the creation of random vehicles 
false = disabled
true = enabled
]]
Config.RandomVehicles = {
	CreateGarbageTrucks = true, -- Enable/disable garbage trucks spawning
	CreateRandomCops = false, -- Enable/disable random cops spawning
	CreateRandomCopsNotOnScenarios = false, -- Enable/disable random cops that aren't part of scenarios
	CreateRandomCopsOnScenarios = false, -- Enable/disable random cops that are part of scenarios
	CreateRandomBoats = false, -- Enable/disable random boats spawning
	CreateVehicleDistantLights = false, -- Enable/disable distant vehicle lights
}

--[[
Settings for specific zones. MAX 15 zones. 
]]
Config.SpecialZones = {
	Enabled = true, -- Master switch for NPC-free zones
	Zones = {
		{
			Name = 'Pillbox Hill Hospital', -- Name for the zone (for identification)
			Debug = false, -- Draws a sphere around zone for testing
			Coords = vector3(312.83, -595.78, 43.28), -- Center coordinates of the zone
			Radius = 45.0, -- Radius of the zone in meters
			PedLevel = 0.0, -- Population level for this zone. 0.0 disables peds from spawning (they can still exist in the area)
			VehicleLevel = 0.0, -- Vehicle generation level for this zone. 0.0 disables vehicles from spawning (they can still exist in the area)
			ForceRemovePeds = false, -- Performance heavy, removes any peds that enter the zone. Use only if above settings arent enough
			ForceRemoveVehicles = false, -- Performance heavy, removes any vehicles that enter the zone. Use only if aboved settings arent enough
		},
		{
			Name = 'Drift Track - Docks',
			Debug = false,
			Coords = vector3(990.23, -3175.37, 5.90),
			Radius = 350.0,
			PedLevel = 0.0,
			VehicleLevel = 0.0,
			ForceRemovePeds = false,
			ForceRemoveVehicles = false,
		},
	},
}
